"""delete image_id

Revision ID: d0aed15c5318
Revises: 7217746e2cdf
Create Date: 2023-08-04 01:37:26.407766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0aed15c5318'
down_revision = '7217746e2cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('image_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), autoincrement=False))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), autoincrement=False))

    # ### end Alembic commands ###
